### ISSUE TITLE
[3] Create working GUI

### ISSUE THREAD

**Issue by istonevol** [COSCS340/OoT_Randomiser#9]
Implement working project into a user-friendly application. Cross platform if possible.

**Comment by DemiMarie** [comment]
Will do, using QT Creator.

On Feb 12, 2018 12:40 PM, "istonevol" <notifications@github.com> wrote:

Assigned #9 <https://github.com/COSCS340/OoT_Randomiser/issues/9> to
@DemiMarie <https://github.com/demimarie>.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/COSCS340/OoT_Randomiser/issues/9#event-1469989661>, or mute
the thread

**Comment by DemiMarie** [comment]
Fixed by #20
